# Generated by Django 4.2.1 on 2023-06-04 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0002_remove_question_vacancy_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas_code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gas',
            },
        ),
        migrations.CreateModel(
            name='GasStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.DecimalField(decimal_places=2, max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
                ('gas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.gas')),
            ],
            options={
                'db_table': 'gas_status',
            },
        ),
    ]
