# Generated by Django 4.2.1 on 2023-06-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_gasstatus_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasstatus',
            name='percent',
            field=models.CharField(max_length=6),
        ),
    ]
